In [127]:
# Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [128]:
# import dataset
df=pd.read_csv('Data.csv')
n=df.iloc[:,:]

In [129]:
# define dependend and independent variable
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [85]:
x,y

(array([['France', 44.0, 72000.0],
        ['Spain', 27.0, 48000.0],
        ['Germany', 30.0, 54000.0],
        ['Spain', 38.0, 61000.0],
        ['Germany', 40.0, nan],
        ['France', 35.0, 58000.0],
        ['Spain', nan, 52000.0],
        ['France', 48.0, 79000.0],
        ['Germany', 50.0, 83000.0],
        ['France', 37.0, 67000.0]], dtype=object),
 array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
       dtype=object))

In [ ]:
# handling missing data

In [41]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [34]:
df.fillna('zz')

Country Age Salary Purchased
0       zz  44  72000        No
1    Spain  27  48000       Yes
2  Germany  30  54000        No
3    Spain  38  61000        No
4  Germany  40     zz       Yes
5       zz  35  58000       Yes
6    Spain  zz  52000        No
7       zz  48  79000       Yes
8  Germany  50  83000        No
9       zz  37  67000       Yes

In [33]:
df.replace('France',np.nan)

In [146]:
from sklearn.preprocessing import Imputer
im=Imputer(strategy='mean')

In [147]:
x[:,1:3] = im.fit_transform(x[:,1:3])

In [148]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [ ]:
# encoding categorical data

In [130]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [155]:
lb_x=LabelEncoder() #object from the class
oh=OneHotEncoder(categorical_features=[0])

In [159]:
x[:,0]=lb_x.fit_transform(x[:,0])

In [167]:
type(lb.fit_transform(x[:,0]))

numpy.ndarray

In [157]:
oh.fit_transform(x).toarray()

C:\Users\hebaa\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [158]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [ ]:
y[:,0]=lb.fit_transform(y[:,0])

In [162]:
lb_y=LabelEncoder()

In [175]:
y=lb_y.fit_transform(y)

In [166]:
lb.fit_transform(x[:,0])

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0])

In [176]:
x,y

(array([[0, 44.0, 72000.0],
        [2, 27.0, 48000.0],
        [1, 30.0, 54000.0],
        [2, 38.0, 61000.0],
        [1, 40.0, 63777.77777777778],
        [0, 35.0, 58000.0],
        [2, 38.77777777777778, 52000.0],
        [0, 48.0, 79000.0],
        [1, 50.0, 83000.0],
        [0, 37.0, 67000.0]], dtype=object),
 array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1]))

In [172]:
# splitting dataset into training and test datasets

In [173]:
from sklearn.model_selection import train_test_split

In [188]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [189]:
x_train,x_test,y_train,y_test

(array([[1, 40.0, 63777.77777777778],
        [0, 37.0, 67000.0],
        [2, 27.0, 48000.0],
        [2, 38.77777777777778, 52000.0],
        [0, 48.0, 79000.0],
        [2, 38.0, 61000.0],
        [0, 44.0, 72000.0],
        [0, 35.0, 58000.0]], dtype=object), array([[1, 30.0, 54000.0],
        [1, 50.0, 83000.0]], dtype=object), array([1, 1, 1, 0, 1, 0, 0, 1]), array([0, 0]))

In [ ]:
# feature scalling

In [192]:
from sklearn.preprocessing import StandardScaler

In [193]:
sc_x=StandardScaler()

In [ ]:
X_train=sc_x.fit_transform(X_train)
X_test=sc_x.transform(X_test)